from pathlib import Path
import html, json

ROOT = Path(__file__).resolve().parents[1]
BASE = "https://toyo-services-psi.vercel.app"

articles = [
 {
  "slug":"mantenimiento-preventivo-toyota-cartagena","title":"Mantenimiento preventivo Toyota en Cartagena: guía por sistemas","description":"Guía completa de mantenimiento preventivo Toyota en Cartagena: qué revisar por kilometraje, condiciones severas, fluidos, frenos, batería y refrigeración.","category":"Mantenimiento","read":"10 min","image":"toyota-hilux-hero.webp",
  "intro":"Un Toyota puede conservar su confiabilidad durante muchos años cuando el mantenimiento responde al modelo, al kilometraje y al uso real. En Cartagena, el calor, la humedad, los recorridos cortos y el tráfico sostenido justifican una revisión más consciente que limitarse a cambiar aceite.",
  "sections":[
   ("El plan correcto comienza con el vehículo",["El manual del propietario y el historial son la referencia inicial. El año, motor, transmisión y versión determinan especificaciones diferentes; por eso no conviene aplicar una lista universal.","Una inspección profesional organiza lo urgente, lo próximo y lo que puede vigilarse. Así se evita reemplazar piezas sin necesidad y también posponer componentes que sí afectan seguridad o confiabilidad."]),
   ("Qué debe incluir una revisión integral",["Aceite y filtros; niveles y condición de refrigerante, líquido de frenos y fluidos de transmisión; estado de batería, correas, mangueras, luces, limpiaparabrisas y posibles fugas.","En la parte dinámica se revisan frenos, llantas, dirección, amortiguadores, bujes, rodamientos y comportamiento durante una prueba de manejo. Un ruido o vibración necesita ubicación y causa, no una pieza elegida por intuición."]),
   ("Uso severo en Cartagena",["Mucho tiempo en ralentí, trayectos cortos, polvo, carga frecuente y tráfico lento pueden exigir intervalos de inspección más cercanos. El kilometraje por sí solo no refleja las horas que el motor permanece encendido.","La humedad y el ambiente costero también justifican observar conexiones, terminales, bajos y puntos donde puede comenzar corrosión. La prevención se basa en evidencia visible, no en asumir que todo vehículo costero está afectado."]),
   ("Cómo construir un historial útil",["Registra fecha, kilometraje, especificación del fluido, referencia del filtro, piezas instaladas y recomendaciones pendientes. Ese historial facilita diagnósticos futuros y ayuda a conservar el valor del vehículo.","Si acabas de comprar un Toyota usado sin antecedentes claros, conviene establecer una línea base: inspección, escaneo, revisión de fluidos y comprobación de elementos de seguridad antes de planear mejoras estéticas o accesorios."])
  ],"faqs":[("¿Cada cuánto debo llevar mi Toyota?","Depende del modelo, manual y tipo de uso. Deben considerarse kilometraje y tiempo, además de condiciones severas como tráfico, carga o recorridos cortos."),("¿El mantenimiento preventivo evita todas las fallas?","No garantiza que nunca ocurra una avería, pero permite detectar desgaste, fugas y cambios de comportamiento antes de que avancen."),("¿Atienden pickups y SUV Toyota?","Sí. Toyo Services trabaja exclusivamente con automóviles, pickups, SUV y vehículos Toyota de trabajo, sujetos a evaluación técnica.")]
 },
 {
  "slug":"mecanica-avanzada-toyota-cartagena","title":"Mecánica avanzada Toyota en Cartagena: diagnóstico antes de reparar","description":"Cómo se diagnostican fallas complejas de motor, transmisión, refrigeración y electrónica Toyota antes de autorizar una reparación.","category":"Mecánica avanzada","read":"11 min","image":"motor-toyota.webp",
  "intro":"Una falla compleja no se resuelve cambiando piezas hasta acertar. La mecánica avanzada combina entrevista, inspección, datos electrónicos, mediciones y pruebas mecánicas para demostrar la causa antes de definir una reparación.",
  "sections":[
   ("Síntoma, código y causa no son lo mismo",["El conductor percibe un síntoma: pérdida de potencia, consumo, humo, ruido, temperatura o una luz de advertencia. El escáner puede registrar códigos, pero esos códigos señalan circuitos o condiciones; rara vez ordenan por sí solos qué pieza cambiar.","El diagnóstico relaciona el momento de la falla, datos en vivo, inspección física y pruebas dirigidas. Un código de mezcla, por ejemplo, puede involucrar entrada de aire, combustible, sensor, cableado o condición mecánica."]),
   ("Pruebas que pueden ser necesarias",["Según el caso se revisan presión, compresión, vacío, temperatura, alimentación eléctrica, continuidad, señales de sensores, fugas y parámetros de funcionamiento. No todas las pruebas aplican a todos los vehículos.","En transmisión se analiza nivel y condición del fluido cuando el diseño lo permite, soportes, códigos, temperaturas, respuesta al engranar y comportamiento en ruta. Abrir un conjunto sin diagnóstico previo puede aumentar costo y tiempo."]),
   ("Cuándo detener el vehículo",["Una advertencia roja de presión de aceite, temperatura fuera de rango, pérdida fuerte de tracción, olor intenso a combustible o ruido mecánico severo exige detenerse con seguridad. Continuar puede convertir una falla localizada en daño mayor.","Una luz amarilla fija suele permitir buscar diagnóstico con precaución, pero si parpadea o el motor funciona de forma muy irregular debe reducirse el riesgo y solicitar asistencia."]),
   ("Presupuesto y alcance",["Una reparación profesional separa diagnóstico, repuestos, mano de obra y trabajos adicionales condicionados a lo que se encuentre. El cliente debe saber qué se comprobó y por qué se recomienda cada intervención.","Toyo Services concentra esta metodología en Toyota para reconocer configuraciones, especificaciones y patrones de la marca sin presentar el taller como concesionario oficial."])
  ],"faqs":[("¿Un escaneo diagnostica por completo el vehículo?","No. El escaneo aporta códigos y datos; deben interpretarse y comprobarse con inspecciones o mediciones."),("¿Pueden reparar motor y transmisión?","Se evalúan fallas y reparaciones de motor y transmisión Toyota. El alcance final depende del diagnóstico, disponibilidad de repuestos y condición del conjunto."),("¿Debo seguir conduciendo con el check engine encendido?","Depende de cómo se comporte y si la luz está fija o parpadea. Si hay pérdida fuerte de potencia, ruido, olor o la luz parpadea, evita continuar y solicita revisión.")]
 },
 {
  "slug":"repuestos-toyota-originales-homologados-cartagena","title":"Repuestos Toyota en Cartagena: originales, OEM y homologados","description":"Aprende a elegir repuestos Toyota originales, OEM u homologados según referencia, sistema, uso, garantía y disponibilidad en Cartagena.","category":"Repuestos","read":"10 min","image":"motor-toyota.webp",
  "intro":"Elegir un repuesto no consiste solo en encontrar una pieza que físicamente encaje. Referencia, especificación, material, tolerancias y compatibilidad electrónica pueden cambiar entre años, motores y versiones del mismo modelo Toyota.",
  "sections":[
   ("Qué significa cada alternativa",["Un repuesto genuino se comercializa bajo la marca del fabricante del vehículo. OEM suele referirse al fabricante que produce componentes para equipo original, mientras homologado o aftermarket abarca alternativas de distintas calidades.","Estas categorías no permiten concluir automáticamente qué opción conviene. En piezas críticas se priorizan especificación, trazabilidad, reputación del fabricante y compatibilidad confirmada."]),
   ("Identificación correcta",["La placa, VIN, modelo, año, motor, transmisión y referencia de la pieza retirada ayudan a evitar errores. Algunas variantes cambian conectores, diámetros, relaciones, calibraciones o soportes aunque el nombre comercial sea idéntico.","En componentes electrónicos también puede requerirse programación, aprendizaje o calibración después de instalar. El repuesto correcto sin el procedimiento correcto puede generar nuevas advertencias."]),
   ("Dónde no conviene improvisar",["Frenos, dirección, distribución, sensores críticos, soportes, refrigeración y componentes internos del motor merecen especial cuidado. Una diferencia pequeña puede afectar seguridad o durabilidad.","Filtros, fluidos y sellos también deben respetar norma y medida. El color de un líquido no demuestra su especificación y dos filtros parecidos pueden tener válvulas o capacidades distintas."]),
   ("Cotización transparente",["Una propuesta clara indica marca, referencia cuando sea posible, cantidad, mano de obra y alcance de garantía. También debe explicar si la disponibilidad obliga a pedir la pieza o si existe una alternativa técnicamente equivalente.","Toyo Services suministra e instala repuestos para sistemas Toyota y presenta opciones según disponibilidad y evaluación, sin prometer que cualquier pieza sirve para cualquier versión."])
  ],"faqs":[("¿Siempre debo instalar repuesto genuino Toyota?","No existe una respuesta única. Para algunos sistemas es la opción preferible; en otros puede haber fabricantes OEM u homologados confiables. La decisión depende de criticidad y especificación."),("¿Puedo llevar mi propio repuesto?","Debe consultarse antes. Es necesario verificar referencia, estado y compatibilidad, además de definir la responsabilidad sobre la pieza suministrada por el cliente."),("¿Cómo evitan pedir una pieza equivocada?","Se cruza la información del vehículo, referencia, sistema y muestra cuando está disponible antes de confirmar la compra.")]
 },
 {
  "slug":"accesorios-toyota-cartagena-guia","title":"Accesorios Toyota en Cartagena: cómo elegir e instalar sin improvisar","description":"Guía de accesorios Toyota en Cartagena: iluminación, cámaras, multimedia, estribos, barras, protectores y soluciones de carga.","category":"Accesorios","read":"9 min","image":"toyota-hilux-hero.webp",
  "intro":"Un accesorio bien elegido debe resolver una necesidad sin comprometer seguridad, electricidad, visibilidad ni uso cotidiano. La compatibilidad con modelo y versión es tan importante como el diseño.",
  "sections":[
   ("Define primero el objetivo",["Trabajo, viajes, familia, carga, ciudad y uso 4x4 requieren soluciones distintas. Un portaequipaje puede ser útil para viajes pero añadir ruido y altura; una luz auxiliar puede mejorar un entorno privado pero debe instalarse y utilizarse respetando normas.","Antes de comprar se revisan medidas, puntos de anclaje, capacidad, interferencias y mantenimiento futuro."]),
   ("Accesorios eléctricos y multimedia",["Cámaras, sensores, pantallas, cargadores e iluminación deben integrarse con fusibles, calibre de cable y conexiones apropiadas. Cortar cableado o tomar alimentación sin protección puede provocar fallas intermitentes.","En vehículos con redes electrónicas se evita interferir con módulos, airbags o señales. También se comprueba consumo en reposo para proteger la batería."]),
   ("Equipamiento exterior",["Estribos, barras, protectores y soluciones de carga necesitan fijaciones adecuadas y revisión periódica. No deben ocultar luces, placas, sensores ni limitar ángulos de apertura.","El peso añadido y su ubicación modifican comportamiento. En accesorios grandes conviene considerar capacidad de carga, altura y centro de gravedad."]),
   ("Instalación y entrega",["Una instalación limpia incluye ruta protegida de cables, tornillería correcta, ausencia de vibraciones y prueba de todas las funciones. El propietario debe conocer uso, límites y mantenimiento.","Toyo Services evalúa accesorios compatibles para Toyota y puede combinar equipamiento con actualizaciones estéticas o transformaciones funcionales."])
  ],"faqs":[("¿Instalan cámaras y pantallas?","Sí, sujeto a compatibilidad con el modelo, versión, sistema eléctrico y equipo seleccionado."),("¿Un accesorio puede afectar la garantía del vehículo?","Depende de la garantía aplicable y de cómo se instale. En vehículos cubiertos conviene revisar sus condiciones antes de modificar sistemas."),("¿Puedo instalar accesorios comprados por internet?","Primero debe verificarse compatibilidad, calidad, elementos incluidos y condiciones de instalación.")]
 },
 {
  "slug":"transformaciones-toyota-hilux-4x4-cartagena","title":"Transformaciones Toyota Hilux y 4x4 en Cartagena: planificación segura","description":"Guía para transformar Toyota Hilux, Fortuner, Prado y otros 4x4: suspensión, protección, carga, iluminación y compatibilidad.","category":"Transformaciones","read":"12 min","image":"toyota-hilux-hero.webp",
  "intro":"Transformar un Toyota 4x4 debe comenzar por el uso real, no por una lista de piezas. Trabajo pesado, carretera, trocha, playa y viaje prolongado plantean cargas y prioridades diferentes.",
  "sections":[
   ("Proyecto antes que accesorios sueltos",["Se define objetivo, carga habitual, pasajeros, terreno, presupuesto y reversibilidad. Después se ordenan fases para evitar comprar dos veces o crear incompatibilidades.","Suspensión, llantas, protecciones, iluminación y carga se influyen entre sí. Elevar o añadir peso sin considerar alineación, frenado y geometría puede deteriorar conducción."]),
   ("Suspensión y capacidad",["La altura no es el único criterio. Importan tasa de resorte, recorrido, amortiguación, peso constante y confort. Una configuración demasiado rígida puede comportarse mal cuando el vehículo está vacío.","Después de intervenir se revisan torque, alineación, mangueras, cableado, ángulos y espacio de llanta durante giro y compresión."]),
   ("Protección e iluminación",["Protectores inferiores deben fijarse en puntos capaces y permitir mantenimiento. Barras y defensas no deben interferir con refrigeración, sensores o seguridad.","La iluminación auxiliar requiere circuito independiente protegido, relé cuando aplique, mando accesible y orientación responsable. Potencia sin control puede deslumbrar o sobrecargar el sistema."]),
   ("Legalidad, seguridad y mantenimiento",["Antes de modificar dimensiones, iluminación o elementos externos deben revisarse las reglas aplicables y condiciones de seguro o garantía. Toyo Services no sustituye la homologación exigida por una autoridad.","Una transformación necesita inspecciones posteriores: fijaciones, fugas, desgaste de llantas, alineación y conexiones. El proyecto termina cuando el conjunto funciona de forma coherente."])
  ],"faqs":[("¿Pueden transformar una Toyota Hilux para trabajo?","Sí. Se diseña según carga, rutas y necesidades, sujeto a evaluación técnica y disponibilidad de componentes."),("¿Toda elevación mejora el 4x4?","No. Puede aumentar despeje, pero también cambia geometría, centro de gravedad y desgaste. Debe plantearse como sistema."),("¿Instalan iluminación auxiliar?","Sí, cuando el equipo es compatible y puede integrarse con protección eléctrica y uso responsable.")]
 },
 {
  "slug":"actualizacion-estetica-toyota-cartagena","title":"Actualización estética Toyota en Cartagena: renovar sin perder identidad","description":"Opciones para actualizar estética exterior e interior Toyota: iluminación, molduras, acabados, restauración e integración visual.","category":"Estética","read":"9 min","image":"toyota-corolla.webp",
  "intro":"Actualizar la apariencia de un Toyota no significa convertirlo en otro vehículo. Un buen proyecto mejora detalles envejecidos y añade elementos compatibles sin crear una mezcla visual ni afectar funciones.",
  "sections":[
   ("Evaluación del estado actual",["Se revisan pintura, faros, molduras, emblemas, plásticos, tapicería, iluminación y reparaciones previas. Restaurar una pieza original puede dar mejor resultado que cubrirla con un accesorio.","También se identifican sensores, cámaras, airbags y puntos de desmontaje para no afectar sistemas durante el trabajo."]),
   ("Exterior coherente",["Iluminación, parrillas, protectores, barras y detalles deben respetar proporciones y versión. Color, textura y terminación de cada pieza determinan si la actualización parece integrada.","Los faros requieren patrón, orientación y compatibilidad eléctrica. Más intensidad no equivale a mejor iluminación si dispersa o deslumbra."]),
   ("Interior y tecnología",["Pantallas, cámaras, iluminación ambiental y renovación de superficies pueden modernizar el uso diario. Se prioriza ergonomía, visibilidad, controles accesibles y cableado oculto.","No se deben cubrir testigos, salidas de airbag ni zonas de ventilación. Las modificaciones deben permitir mantenimiento posterior."]),
   ("Plan por etapas",["Un proyecto puede dividirse en restauración, funcionalidad y detalles finales. Esto permite evaluar cada resultado y mantener consistencia.","Toyo Services combina actualización estética, accesorios y correcciones mecánicas para que la presentación del vehículo acompañe su condición técnica."])
  ],"faqs":[("¿Pueden actualizar un Toyota antiguo?","Sí, después de evaluar estado, disponibilidad de piezas y compatibilidad. Se priorizan seguridad y funcionamiento."),("¿Cambiar bombillos por LED siempre funciona?","No. Óptica, patrón, disipación, espacio y sistema eléctrico deben ser compatibles."),("¿Hacen proyectos por etapas?","Sí. Se puede priorizar restauración, funcionalidad y acabados según presupuesto y disponibilidad.")]
 },
 {
  "slug":"suspension-toyota-ruidos-vibraciones-cartagena","title":"Suspensión Toyota: ruidos, vibraciones y señales de desgaste","description":"Cómo identificar ruidos y desgaste en suspensión y dirección Toyota: amortiguadores, bujes, terminales, rodamientos y alineación.","category":"Suspensión","read":"10 min","image":"toyota-corolla.webp",
  "intro":"Un ruido al pasar un desnivel no identifica por sí solo un amortiguador. La suspensión y dirección contienen piezas que trabajan juntas; holguras, llantas, frenos y fijaciones pueden producir sensaciones parecidas.",
  "sections":[
   ("Cómo describir el síntoma",["Anota si ocurre al girar, frenar, acelerar, pasar baches o circular a cierta velocidad. También importa si es golpe seco, zumbido, crujido o vibración.","La ubicación percibida dentro de la cabina puede engañar. Una prueba controlada y una inspección con carga ayudan a reproducir el problema."]),
   ("Componentes que se revisan",["Amortiguadores, resortes, bases, bujes, rótulas, terminales, brazos, barras estabilizadoras y rodamientos. También llantas, rines, torque y posibles roces.","Una pieza con caucho agrietado no siempre está funcionalmente agotada; se evalúa holgura, movimiento y efecto real antes de reemplazar."]),
   ("Vibración y alineación",["La vibración por velocidad puede relacionarse con balanceo, deformación, rin o rodamiento. Al frenar puede involucrar discos, bujes o montaje. En aceleración se consideran ejes, soportes y transmisión.","Alinear sin corregir holguras puede producir un resultado temporal. Primero se inspecciona, después se corrige y finalmente se alinea cuando corresponde."]),
   ("Después de la reparación",["Se verifican torque, altura, alineación y prueba de manejo. Algunas fijaciones con bujes deben apretarse en posición de trabajo para evitar precarga.","En transformaciones 4x4, la suspensión debe revisarse como conjunto con peso, llantas y geometría."])
  ],"faqs":[("¿Todo ruido al pasar un bache es amortiguador?","No. Puede provenir de bujes, bases, barras, frenos, dirección u objetos sueltos. Debe reproducirse e inspeccionarse."),("¿Debo alinear después de cambiar suspensión?","Con frecuencia sí, según el componente intervenido. Primero deben eliminarse holguras."),("¿Una vibración siempre es balanceo?","No. También puede involucrar llantas deformadas, rines, rodamientos, frenos, ejes o soportes.")]
 },
 {
  "slug":"frenos-toyota-mantenimiento-cartagena","title":"Frenos Toyota en Cartagena: mantenimiento, síntomas y diagnóstico","description":"Guía completa de frenos Toyota: pastillas, discos, líquido, vibraciones, ruidos y señales que requieren revisión inmediata.","category":"Frenos","read":"10 min","image":"toyota-corolla.webp",
  "intro":"El sistema de frenos debe evaluarse por capacidad, equilibrio y condición, no solo por el grosor de una pastilla. Pedal, líquido, discos, mangueras, sensores y llantas influyen en la respuesta.",
  "sections":[
   ("Señales que no deben ignorarse",["Pedal que se hunde, pérdida de respuesta, desviación fuerte, fuga o advertencia roja requieren detener el vehículo con seguridad. Un chirrido leve puede tener varias causas, pero debe revisarse si persiste.","La vibración al frenar puede relacionarse con variación del disco, montaje, bujes o llanta. Cambiar discos sin comprobar el conjunto puede hacer que el síntoma regrese."]),
   ("Inspección completa",["Se revisan pastillas, discos o campanas, cálipers, guías, mangueras, tuberías, líquido, fugas y freno de estacionamiento. En sistemas electrónicos se consultan advertencias y datos cuando aplica.","El desgaste desigual entre ruedas puede indicar guía trabada, pistón, manguera o condición de montaje."]),
   ("Líquido y procedimiento",["El líquido absorbe humedad con el tiempo y su condición no se juzga solo por color. Se usa la especificación indicada y se purga con método compatible con el sistema.","Contaminar con aceite o producto incorrecto puede dañar sellos. Los envases y herramientas deben mantenerse limpios."]),
   ("Asentamiento y verificación",["Después de reemplazar componentes se comprueba pedal, fugas, torque y funcionamiento. Pastillas y discos nuevos pueden requerir asentamiento progresivo según fabricante.","El conductor recibe indicaciones y debe regresar si aparece pérdida de respuesta, ruido anormal o advertencia."])
  ],"faqs":[("¿Puedo conducir si el pedal se siente esponjoso?","No es recomendable. Puede existir aire, fuga u otra condición que reduzca frenado; requiere revisión inmediata."),("¿Siempre se rectifican los discos?","No. Depende de espesor, variación, daño y especificación. Algunos deben reemplazarse."),("¿Por qué una pastilla se gasta más que la otra?","Puede haber guías, pistón, manguera o montaje con movimiento restringido. Debe corregirse la causa.")]
 },
 {
  "slug":"sistema-refrigeracion-toyota-cartagena","title":"Sistema de refrigeración Toyota en Cartagena: evitar recalentamientos","description":"Cómo cuidar radiador, refrigerante, termostato, bomba, ventiladores y mangueras Toyota frente al calor y tráfico de Cartagena.","category":"Refrigeración","read":"10 min","image":"motor-toyota.webp",
  "intro":"En el clima de Cartagena el sistema de refrigeración trabaja con alta carga térmica, especialmente en tráfico y con aire acondicionado. Una temperatura anormal nunca debe tratarse como algo normal del clima.",
  "sections":[
   ("Cómo circula y controla la temperatura",["Refrigerante, bomba, termostato, radiador, ventiladores, tapa, mangueras y sensores forman un circuito. Una falla en cualquiera puede producir pérdida, presión incorrecta o falta de intercambio térmico.","El tablero puede mostrar la consecuencia tarde. Por eso una inspección preventiva observa niveles, residuos, fugas secas, estado de mangueras y funcionamiento de ventiladores."]),
   ("Refrigerante correcto",["No debe elegirse solo por color. La química y especificación importan para metales, sellos y protección contra corrosión. Mezclar productos incompatibles puede crear depósitos.","Rellenar repetidamente sin localizar la pérdida solo aplaza el problema. Un circuito sellado no debería consumir refrigerante de forma continua."]),
   ("Qué hacer si aumenta la temperatura",["Apaga el aire acondicionado, busca un lugar seguro y detén el motor si la temperatura sigue subiendo o aparece advertencia. No abras la tapa en caliente: el sistema presurizado puede causar quemaduras.","Después de un recalentamiento se debe comprobar causa y posibles consecuencias, no únicamente completar nivel."]),
   ("Prevención en tráfico costero",["Mantén limpio el paso de aire, revisa ventiladores, batería y carga eléctrica, y atiende fugas u olores dulces. El aire acondicionado y la refrigeración comparten flujo frontal en muchos vehículos.","Una prueba de presión o verificación de gases se utiliza cuando los síntomas lo justifican; no es necesaria de forma indiscriminada."])
  ],"faqs":[("¿Puedo usar agua sola?","Solo puede ser una medida de emergencia según la situación. Para operación normal se utiliza refrigerante con especificación y mezcla correctas."),("¿Es normal completar refrigerante cada mes?","No. Una pérdida repetida necesita diagnóstico, aunque no deje charco visible."),("¿Puedo abrir la tapa cuando está caliente?","No. Existe riesgo de expulsión de líquido a presión y quemaduras graves.")]
 },
 {
  "slug":"check-engine-diagnostico-electronico-toyota","title":"Check Engine Toyota: qué significa y cómo se diagnostica","description":"Qué hacer cuando enciende el Check Engine de un Toyota, diferencia entre luz fija y parpadeante, códigos OBD y diagnóstico electrónico.","category":"Diagnóstico","read":"11 min","image":"motor-toyota.webp",
  "intro":"La luz Check Engine informa que un módulo detectó una condición fuera de rango. No nombra una pieza y tampoco debe borrarse sin registrar la información que puede ayudar a encontrar la causa.",
  "sections":[
   ("Luz fija o parpadeante",["Una luz fija con funcionamiento normal suele permitir programar diagnóstico pronto y conducir con moderación. Una luz parpadeante puede indicar una falla capaz de dañar el catalizador; si hay tirones, olor o pérdida de potencia, evita continuar.","Advertencias rojas de aceite o temperatura son diferentes y requieren respuesta inmediata. El manual del vehículo explica cada testigo."]),
   ("Qué aporta el escáner",["Registra códigos, datos congelados del momento de la falla y parámetros en vivo. También permite saber si los monitores están listos y si la falla es actual, pendiente o histórica.","Borrar códigos elimina pistas y reinicia monitores; no repara la causa. Desconectar batería también puede perder adaptaciones o información."]),
   ("Proceso de diagnóstico",["Se confirma la queja, inspeccionan conexiones y mangueras, consultan datos y se diseñan pruebas. Dependiendo del código se mide alimentación, tierra, señal, presión, fugas o condición mecánica.","La pieza mencionada en la descripción del código puede estar reportando correctamente un problema originado en otro lugar."]),
   ("Después de corregir",["Se borran códigos cuando corresponde, se prueba el vehículo y se verifica que los parámetros vuelvan a rango. Algunos monitores necesitan ciclos de conducción para completar.","Si la luz regresa, se conserva el contexto y se continúa el diagnóstico en lugar de repetir la misma pieza."])
  ],"faqs":[("¿Puedo borrar el Check Engine y seguir?","Borrarlo no corrige la causa y puede eliminar información útil. Primero conviene registrar códigos y datos."),("¿El código dice exactamente qué pieza cambiar?","Normalmente no. Indica un circuito o condición que debe comprobarse."),("¿Una tapa de combustible puede encender la luz?","En algunos sistemas evaporativos sí, pero no debe asumirse sin consultar el código y revisar el sistema.")]
 }
]

existing = [
 ("cada-cuanto-cambiar-aceite-toyota","¿Cada cuánto cambiar el aceite de un Toyota?","Aceite","5 min","motor-toyota.webp","Intervalos, señales y factores de uso que debes considerar."),
 ("senales-transmision-toyota","Señales de una transmisión Toyota que pide revisión","Transmisión","6 min","toyota-corolla.webp","Tirones, demoras, fugas y cambios de comportamiento que requieren diagnóstico."),
 ("mantenimiento-toyota-cartagena","Mantenimiento Toyota para el clima de Cartagena","Cartagena","6 min","motor-toyota.webp","Calor, humedad, tráfico y trayectos cortos: qué sistemas debes vigilar.")
]

extras = {
 "Mantenimiento":[
  ("Cómo priorizar cuando hay varias recomendaciones",["Primero se atienden condiciones de seguridad, fugas activas, temperatura, lubricación y fallas que pueden causar daños mayores. Después se organizan elementos de confiabilidad y, finalmente, trabajos de confort o apariencia. Esta jerarquía permite usar el presupuesto con criterio.","No todo hallazgo exige reemplazo inmediato. Una recomendación debe indicar condición, riesgo, margen de uso razonable y forma de seguimiento. Fotografías, medidas o una explicación visible ayudan al propietario a decidir sin presión."]),
  ("Preparación para una revisión eficiente",["Lleva el historial disponible y explica cuándo aparece cada síntoma, si ocurre en frío o caliente, con aire acondicionado, carga o determinada velocidad. Evita limpiar una fuga justo antes de la visita porque puede ocultar evidencia útil.","Retira objetos pesados o sueltos si se evaluarán ruidos y confirma el nivel habitual de combustible. Al recibir el vehículo, revisa qué se realizó, qué quedó pendiente y cuándo debe comprobarse de nuevo."])
 ],
 "Mecánica avanzada":[
  ("Errores que encarecen una reparación",["Cambiar sensores por el nombre de un código, mezclar fluidos, borrar información antes de escanear o continuar conduciendo con temperatura o presión anormales puede aumentar el alcance. También dificulta el diagnóstico instalar piezas usadas sin referencia clara.","Una segunda opinión es útil cuando la propuesta no explica pruebas ni causa. Lo importante no es acumular opiniones sino comparar evidencia: valores medidos, condición encontrada y relación lógica con el síntoma."]),
  ("Cómo se confirma que la reparación funcionó",["La verificación puede incluir arranque en frío, temperatura de operación, prueba de ruta, datos en vivo, ausencia de fugas y repetición de la condición que generaba la falla. Un código borrado no es prueba suficiente.","Algunas reparaciones requieren reaprendizajes o ciclos de conducción. El cliente debe saber qué comportamiento puede ser temporal y qué señal indicaría detenerse o regresar al taller."])
 ],
 "Repuestos":[
  ("Piezas económicas y costo total",["El precio de compra es solo una parte. Deben sumarse mano de obra, fluidos, empaques, calibración y riesgo de repetir el trabajo. Una pieza barata que dura poco puede costar más que una alternativa trazable.","Tampoco la opción más costosa es automáticamente mejor. La comparación responsable usa especificación, fabricante, garantía, disponibilidad y criticidad del sistema."]),
  ("Qué conservar después del servicio",["Guarda factura, marca, referencia y empaque cuando sea útil para garantía. Solicita conocer la pieza retirada, salvo que deba devolverse como núcleo o por condición comercial previamente explicada.","Tras instalar, observa fugas, ruidos, advertencias y comportamiento. Algunos componentes necesitan asentamiento, torque de comprobación o inspección posterior."])
 ],
 "Accesorios":[
  ("Compatibilidad con seguridad y mantenimiento",["No deben bloquearse puntos de elevación, acceso a filtros, rueda de repuesto, ganchos o sensores. Un accesorio que obliga a desmontajes excesivos en cada servicio aumenta tiempo y riesgo de daño.","En el habitáculo se protegen zonas de airbag, visibilidad y movimiento de pedales. Cables y módulos deben quedar sujetos, identificables y lejos de humedad o calor."]),
  ("Preguntas antes de comprar",["¿Qué problema resuelve? ¿Es compatible con la versión? ¿Qué incluye el kit? ¿Requiere perforar, programar o cortar cableado? ¿Aumenta altura, peso o consumo eléctrico? Estas respuestas evitan compras impulsivas.","También conviene definir acabado, garantía y disponibilidad de repuestos del accesorio. Una instalación profesional no corrige un producto de baja calidad o sin soporte."])
 ],
 "Transformaciones":[
  ("Orden recomendado del proyecto",["Comienza con mantenimiento y corrección de fallas. Después define carga y suspensión, continúa con protección y ruedas, y deja electrónica, accesorios y estética para una fase compatible con lo anterior.","Este orden puede cambiar según el objetivo, pero evita instalar iluminación antes de dimensionar la energía o elegir suspensión sin conocer el peso final."]),
  ("Prueba y documentación",["Registra referencias, alturas, alineación, torque y conexiones. Una prueba debe incluir maniobras lentas, giro completo, frenado y condiciones normales de carretera antes de exigir el vehículo.","Tras los primeros recorridos se inspeccionan fijaciones, roces, ruidos y asentamiento. Las transformaciones necesitan mantenimiento propio además del plan Toyota original."])
 ],
 "Estética":[
  ("Evitar que una modificación se vea añadida",["La clave está en proporción, temperatura de color, textura y repetición de acabados. Demasiados elementos compiten entre sí; pocos cambios bien integrados suelen producir un resultado más duradero.","Antes de pedir una pieza conviene visualizar tamaño y posición, además de comprobar si existen variantes para la misma carrocería."]),
  ("Cuidado después de actualizar",["Cada material necesita limpieza compatible. Productos agresivos pueden manchar plásticos, atacar adhesivos o deteriorar recubrimientos. El instalador debe explicar curado y mantenimiento.","Revisa fijaciones y sellos después de lluvia o carretera. Si una luz genera condensación, parpadeo o advertencia, debe corregirse en lugar de ocultarse."])
 ],
 "Suspensión":[
  ("Llantas y presión también importan",["Una presión incorrecta cambia confort, desgaste y respuesta. Medidas no equivalentes o llantas con deformación pueden simular problemas de suspensión y afectar calibraciones.","Se revisa desgaste en bordes, escalonamiento, fecha, reparación previa y compatibilidad. Rotar no corrige una pieza con holgura ni una geometría fuera de rango."]),
  ("Ruidos después de una intervención",["Una fijación sin torque, resorte mal asentado, manguera en tensión o protector rozando puede aparecer después de reparar. Documentar el momento exacto facilita localizarlo.","La revisión posterior no debe limitarse al componente nuevo: confirma relación con los elementos vecinos y que el vehículo conserva altura y movimiento adecuados."])
 ],
 "Frenos":[
  ("Hábitos que afectan duración",["Descensos prolongados con el freno aplicado, sobrecarga y conducción con un cáliper restringido elevan temperatura. En carretera se usa una marcha apropiada sin exceder límites del motor y se mantiene distancia.","Lavar componentes muy calientes o contaminar superficies con productos puede afectar respuesta. Cualquier cambio tras una intervención merece inspección."]),
  ("ABS y ayudas electrónicas",["ABS, control de estabilidad y asistencia dependen de sensores, rodamientos, llantas y alimentación eléctrica. Una advertencia no siempre significa que el freno hidráulico desapareció, pero indica que una ayuda puede estar deshabilitada.","El diagnóstico consulta códigos y señales de rueda, además de cableado y condición mecánica. Cambiar un sensor sin comprobar su señal puede no resolver."])
 ],
 "Refrigeración":[
  ("Relación con el aire acondicionado",["El condensador del aire acondicionado suele estar delante del radiador y ambos dependen del flujo de aire. Suciedad externa, ventiladores débiles o presión incorrecta pueden manifestarse más en tráfico.","No se recarga refrigerante de aire sin diagnosticar. Tampoco se culpa al aire acondicionado de una temperatura alta sin revisar el sistema de motor."]),
  ("Después de cambiar un componente",["Se purga aire con el procedimiento correspondiente, comprueba calefacción cuando aplica, funcionamiento de ventiladores, presión y ausencia de fugas. Una bolsa de aire puede causar lecturas o circulación irregulares.","Al enfriar se verifica nivel nuevamente. El propietario debe observar temperatura y piso donde estaciona durante los primeros recorridos."])
 ],
 "Diagnóstico":[
  ("Códigos históricos y fallas intermitentes",["Un código guardado puede provenir de batería baja, desconexión o evento antiguo. Se compara con fecha, kilometraje, datos congelados y frecuencia antes de atribuirle el síntoma actual.","Las fallas intermitentes requieren capturar condiciones. Anotar temperatura, lluvia, combustible, velocidad y accesorios encendidos puede revelar un patrón."]),
  ("Batería y alimentación eléctrica",["Voltaje bajo puede producir múltiples advertencias y comunicaciones erráticas. Se comprueba batería, arranque, carga, tierras y terminales antes de condenar módulos.","Después de sustituir batería algunos modelos requieren reinicios o aprendizajes. Mantener energía con métodos inadecuados también puede crear riesgos."])
 ]
}

header = '''<header class="site-header"><nav class="nav container"><a class="brand" href="/"><span class="brand-mark">T</span><span>TOYO <span>SERVICES</span></span></a><button class="menu" aria-expanded="false" aria-label="Abrir menú">☰</button><div class="nav-links"><a href="/">Inicio</a><a href="/servicios/">Servicios</a><a aria-current="page" href="/blog/">Guía Toyota</a><a href="/#ubicacion">Ubicación</a></div></nav></header>'''
footer = '''<footer class="footer"><div class="container"><div class="footer-grid"><div><a class="brand" href="/"><span class="brand-mark">T</span><span>TOYO <span>SERVICES</span></span></a><p class="muted">Mantenimiento, mecánica, repuestos y transformación exclusivamente Toyota en Cartagena.</p></div><div><h3>Servicios</h3><a href="/servicios/#mantenimiento-general">Mantenimiento</a><a href="/servicios/#mecanica-avanzada">Mecánica avanzada</a><a href="/servicios/#repuestos">Repuestos</a></div><div><h3>Personalización</h3><a href="/servicios/#transformaciones">Transformaciones</a><a href="/servicios/#accesorios">Accesorios</a><a href="/servicios/#estetica">Estética</a></div></div><div class="legal"><span>© <span data-year></span> Toyo Services.</span><span>Taller independiente no afiliado a Toyota Motor Corporation.</span></div></div></footer><span class="wa-float" title="WhatsApp disponible próximamente" aria-label="WhatsApp disponible próximamente"><img src="/assets/images/whatsapp-logo.png" alt="" aria-hidden="true"></span><script src="/assets/js/main.js?v=6" defer></script>'''

def article_page(a):
    canonical=f"{BASE}/blog/{a['slug']}/"
    faq_schema={"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":q,"acceptedAnswer":{"@type":"Answer","text":ans}} for q,ans in a["faqs"]]}
    posting={"@context":"https://schema.org","@type":"BlogPosting","headline":a["title"],"description":a["description"],"datePublished":"2026-08-06","dateModified":"2026-08-06","author":{"@type":"Organization","name":"Toyo Services"},"publisher":{"@type":"Organization","name":"Toyo Services"},"image":f"{BASE}/assets/images/{a['image']}","mainEntityOfPage":canonical}
    all_sections=a['sections']+extras[a['category']]
    toc=''.join(f'<li><a href="#s{i}">{html.escape(title)}</a></li>' for i,(title,_) in enumerate(all_sections,1))
    body=''
    for i,(title,paragraphs) in enumerate(all_sections,1):
        body+=f'<h2 id="s{i}">{html.escape(title)}</h2>'+''.join(f'<p>{html.escape(p)}</p>' for p in paragraphs)
    faqs=''.join(f'<details><summary>{html.escape(q)}</summary><p>{html.escape(ans)}</p></details>' for q,ans in a['faqs'])
    return f'''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(a['title'])} | Toyo Services</title><meta name="description" content="{html.escape(a['description'])}"><link rel="canonical" href="{canonical}"><meta property="og:type" content="article"><meta property="og:title" content="{html.escape(a['title'])}"><meta property="og:description" content="{html.escape(a['description'])}"><meta property="og:url" content="{canonical}"><meta property="og:image" content="{BASE}/assets/images/{a['image']}"><meta name="theme-color" content="#080a0d"><link rel="icon" href="/assets/images/favicon.svg"><link rel="stylesheet" href="/assets/css/styles.css?v=6"><script type="application/ld+json">{json.dumps(posting,ensure_ascii=False)}</script><script type="application/ld+json">{json.dumps(faq_schema,ensure_ascii=False)}</script></head><body>{header}<main class="article"><nav class="breadcrumb" aria-label="Migas de pan"><a href="/">Inicio</a> / <a href="/blog/">Guía Toyota</a> / {html.escape(a['category'])}</nav><span class="eyebrow">{html.escape(a['category'])} Toyota</span><h1>{html.escape(a['title'])}</h1><p class="lead">{html.escape(a['intro'])}</p><img src="/assets/images/{a['image']}" width="1200" height="800" alt="{html.escape(a['title'])}" fetchpriority="high"><aside class="article-toc"><strong>En esta guía</strong><ol>{toc}</ol></aside>{body}<h2>Una recomendación responsable</h2><p>Esta guía ofrece orientación general y no sustituye la inspección del vehículo. El procedimiento, las referencias y el alcance cambian según modelo, año, versión, historial y condición. En Toyo Services revisamos exclusivamente vehículos Toyota y explicamos el diagnóstico antes de autorizar reparaciones o modificaciones.</p><section class="faq article-faq"><h2>Preguntas frecuentes</h2>{faqs}</section><div class="actions"><a class="btn btn-primary" href="/servicios/">Ver servicios Toyota</a><a class="btn btn-outline" href="/#ubicacion">Ubicación en Cartagena</a></div></main>{footer}</body></html>'''

for article in articles:
    folder=ROOT/'blog'/article['slug']; folder.mkdir(parents=True,exist_ok=True)
    (folder/'index.html').write_text(article_page(article),encoding='utf-8')

cards=[]
for a in articles:
    cards.append((a['slug'],a['title'],a['category'],a['read'],a['image'],a['description']))
cards += existing
card_html=''.join(f'''<article class="card blog-card"><img loading="lazy" src="/assets/images/{img}" width="800" height="500" alt="{html.escape(title)}"><div class="blog-body"><span class="tag">{html.escape(cat)} · {read}</span><h2>{html.escape(title)}</h2><p>{html.escape(desc)}</p><a class="card-link" href="/blog/{slug}/">Leer guía →</a></div></article>''' for slug,title,cat,read,img,desc in cards)
item_schema={"@context":"https://schema.org","@type":"CollectionPage","name":"Guía Toyota de Toyo Services","url":f"{BASE}/blog/","hasPart":[{"@type":"BlogPosting","headline":title,"url":f"{BASE}/blog/{slug}/"} for slug,title,*_ in cards]}
blog=f'''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Guía Toyota: mantenimiento, mecánica y accesorios | Cartagena</title><meta name="description" content="Guías completas sobre mantenimiento, mecánica avanzada, repuestos, accesorios y transformaciones Toyota en Cartagena."><link rel="canonical" href="{BASE}/blog/"><meta name="theme-color" content="#080a0d"><link rel="icon" href="/assets/images/favicon.svg"><link rel="stylesheet" href="/assets/css/styles.css?v=6"><script type="application/ld+json">{json.dumps(item_schema,ensure_ascii=False)}</script></head><body>{header}<main><header class="page-hero"><div class="container"><div class="breadcrumb"><a href="/">Inicio</a> / Guía Toyota</div><span class="eyebrow">Conocimiento Toyota</span><h1>Información para mantener, reparar y transformar tu Toyota.</h1><p>Trece guías creadas para propietarios de Toyota en Cartagena: decisiones de mantenimiento, diagnóstico, repuestos, seguridad, accesorios y proyectos 4x4.</p></div></header><section><div class="container"><div class="blog-grid">{card_html}</div></div></section></main>{footer}</body></html>'''
(ROOT/'blog'/'index.html').write_text(blog,encoding='utf-8')
print(f"Generated {len(articles)} new articles and blog index with {len(cards)} entries")
